### ISSUE TITLE
Initial indent in yaml

### ISSUE THREAD

**Issue by hdadhich01** [macisamuele/language-formatters-pre-commit-hooks#132]
My [local YAML formatter](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) places an initial indent after the parent keyword in a `.pre-commit-config.yaml` file. The `pretty-format-yaml` hook formats it another variant. I was wondering what the reason was for the discrepancy.

Local Formatter
```yaml
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix]
```

Hook Formatter
```yaml
repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
```
