### ISSUE TITLE
How can I pass "java arguments" to the hook? 

### ISSUE THREAD

**Issue by NoFuchsGavin** [macisamuele/language-formatters-pre-commit-hooks#139]
.pre-commit-config.yaml:

```
default_language_version:
  python: python3

repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.4.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
```

Because of OpenJDK 16 feature: https://openjdk.org/jeps/396

I get the following error:

```
Run command: ('java', '--add-exports', 'jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED', '--add-exports', 'jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED', '--add-exports', 'jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED', '--add-exports', 'jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED', '--add-exports', 'jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED', '-jar', 'C:\\Users\\user\\.cache\\pre-commit\\google-java-formatter1.15.0.jar', 
```

And the solution would be to either add the following argument to the java command:

`java --illegal-access=permit`

Or this list of parameters:

```sh
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED
```

How can I do it in this pre-commit hook?
