### ISSUE TITLE
"Offset" is defined in the YAML hook, but is unaccessible from the command line

### ISSUE THREAD

**Issue by Alexander-Serov** [macisamuele/language-formatters-pre-commit-hooks#145]
Hello!

I see the "offset" parameter defined [here](https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/42672673f0bed83269d4465ceac63d24ca9c401a/language_formatters_pre_commit_hooks/pretty_format_yaml.py#L49) for the yaml files. However, when I try to use it in v2.6.0, I get the following message:
```
Pretty format YAML.......................................................Failed
- hook id: pretty-format-yaml
- exit code: 2

usage: pretty-format-yaml
       [-h]
       [--autofix]
       [--indent INDENT]
       [--preserve-quotes]
       [--line-width LINE_WIDTH]
       [filenames [filenames ...]]
pretty-format-yaml: error: unrecognized arguments: --offset
```

My pre-commit-config:
```
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --offset, '2']
```

Am I doing something wrong?
