### ISSUE TITLE
YAML `--preserve-quotes`, changing quotes vs removing quotes

### ISSUE THREAD

**Issue by Avasam** [macisamuele/language-formatters-pre-commit-hooks#153]
I'd like to be able to enforce consistent single vs double quotes (whichever, idc). But I'd also like for existing quotes to not be removed.
Especially for version numbers we pre-emptively quote some entries to avoid accidentally writing something like `python: 3.10` (which is actually `3.1`, not `3.10` !) when upgrading from python 3.9, for example.

**Comment by macisamuele** [comment]
Thanks for the report.
Is this problem still active?
If so, could you share a minimal reproducer of the issue?

**Comment by Avasam** [comment]
`.pre-commint-config.yaml`
```yaml
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.8.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, "2", --offset, "0", --line-width, "120"]
```

`.github/workflows/typecheck.yaml`
```yaml
name: Typecheck

on:
  workflow_dispatch: #  Allows manual triggers
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "**.pyi"
      - "**/requirements*.txt"
      - "**/pyproject.toml"
      - ".github/workflows/typecheck.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "**.pyi"
      - "**/requirements*.txt"
      - "**/pyproject.toml"
      - ".github/workflows/typecheck.yaml" # I want these quotes to stay

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1

jobs:
  pyright:
    name: Run pyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8" # I want these quotes to stay
        cache: pip
        cache-dependency-path: "**/requirements*.txt"
    - run: pip install -r requirements.txt
    - uses: jakebailey/pyright-action@v1
      with:
        project: ./Dolphin scripts/pyproject.toml
```

In the example above, `"` is changed to `'`, that's fine, I don't care as long as it's consistent. But I don't want quotes to be removed.
