### ISSUE TITLE
Option to disable root-level sequence indentation

### ISSUE THREAD

**Issue by denys-kochetkov** [macisamuele/language-formatters-pre-commit-hooks#174]
We run pre-commit YAML formatting on our Ansible playbooks with the following configuration:

```
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --preserve-quotes, --indent, '2', --offset, '2']
```

By default, all sequences are indented, including root-level sequences. So this YAML file:
```
- a: 1
- b: 2
```
Is converted to this with two leading whitespaces:
```
  - a: 1
  - b: 2
```

This was addressed in [this](https://stackoverflow.com/questions/52820367/specific-formatting-of-sequences-in-yaml) Stackoverflow question with a custom transform function, would be nice to have something similar here as well.
