### ISSUE TITLE
Toml parsed incorrectly

### ISSUE THREAD

**Issue by joshua-auchincloss** [macisamuele/language-formatters-pre-commit-hooks#198]
When using the lib with nested tables, the script (`pretty-format-toml`) incorrectly overrides keys of adjacent tables. 

E.g. (this was in a `Cargo.toml`), see `>>` for effected entries

## preformatted
```toml
[package]
name = "client"
readme = "README.md"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
>> version.workspace = true

[package.metadata.release]
shared-version = true
repository.workspace = true
rust-version.workspace = true
```
```toml
[dependencies]
serde = {workspace = true, features = ["derive"]}
sea-orm.workspace = true
>> thiserror.workspace = true

[dependencies.sea-orm-migration]
features = [
  "runtime-tokio-native-tls",
  "sqlx-postgres"
]
workspace = true
```

## formatted
```toml
[package]
name = "client"
readme = "README.md"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[package.metadata.release]
shared-version = true
repository.workspace = true
rust-version.workspace = true
>> version.workspace = true
>> version.workspace = true
```
```toml
[dependencies]
serde = {workspace = true, features = ["derive"]}
sea-orm.workspace = true

[dependencies.sea-orm-migration]
features = [
  "runtime-tokio-native-tls",
  "sqlx-postgres"
]
workspace = true
>> thiserror.workspace = true
```
