### ISSUE TITLE
Checksum for downloaded jars

### ISSUE THREAD

**Issue by mxr** [macisamuele/language-formatters-pre-commit-hooks#216]
Various hooks download jars if they aren't present. Would you consider adding the option to specify a file checksum in addition to a version, to ensure the integrity of downloaded jars? Then after the file is downloaded, the actual checksum would be compared to the one provided in the hook config

The hook config would look something like:
```
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: ${LATEST_SHA_OR_VERSION}
  hooks:
  - id: pretty-format-some-language
    args: [--autofix, --version=1.2.3, --checksum=a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447]
```
