### ISSUE TITLE
Could not determine a constructor for the tag '!reference'

### ISSUE THREAD

**Issue by kokorin** [macisamuele/language-formatters-pre-commit-hooks#229]
We changed Gitlab CI Yaml file and added [!reference](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags) tag like this:

```yaml
deploy-dev:
   script:
    - !reference [.deploy, script]
    - other commands
```

`pre-commit run` gives the following output:

```sh
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 194, column 7
```

I found [a recommendation](https://stackoverflow.com/questions/73932808/load-gitlab-ci-yml-with-pyyaml-fails-with-could-not-determine-constructor) to update ruamel version and added dependencies:

```yaml
default_install_hook_types: [pre-commit, pre-push]
repos:
  # other repos removed
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2', --preserve-quotes]
        stages: [commit]
        additional_dependencies:
          - 'ruamel.yaml==0.18.6'
          - 'ruamel.yaml.clib==0.2.8'
```

Unfortunately that didn't help

Python version 3.9.7
