### ISSUE TITLE
When specifying the version 1.10.0 in the hook args, pretty-format-java hook is not working 

### ISSUE THREAD

**Issue by siddeshbb** [macisamuele/language-formatters-pre-commit-hooks#58]
I know the latest version of google-java-format 1.10.0 is used in this hook.

But when we explicitly specify the version as args in  pretty-format-java hook its failing to download.
```yaml
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: pretty-format-java
        args: [--autofix,--google-java-formatter-version=1.10.0]
```
Terminal Output:
```
RuntimeError: Failed to download https://github.com/google/google-java-format/releases/download/google-java-format-1.10.0/google-java-format-1.10.0-all-deps.jar. Probably the requested version, 1.10.0, is not valid or you have some network issue.
```

I see you are using the below url format in the code
https://github.com/google/google-java-format/releases/download/google-java-format-{version}/google-java-format-{version}-all-deps.jar

But from google java release of 1.10.0 has this below url
https://github.com/google/google-java-format/releases/download/v1.10.0/google-java-format-1.10.0-all-deps.jar
