### ISSUE TITLE
Unexpected ':'

### ISSUE THREAD

**Issue by tdegeus** [macisamuele/language-formatters-pre-commit-hooks#85]
Consider this YAML file:
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: [--max-line-length=100, "--per-file-ignores=python/myrepo/*.py:F401"]
```
The last line is formatted to
```yaml
    args: [--max-line-length=100, --per-file-ignores=python/myrepo/*.py:F401]
```
(the `"..."` are removed). This is however illegal. Indeed `pre-commit-hooks` complains about this:
```none
while scanning a plain scalar
  in ".pre-commit-config.yaml", line 13, column 35
found unexpected ':'
  in ".pre-commit-config.yaml", line 13, column 73
```

Reference: https://github.com/pre-commit/pre-commit-hooks/issues/650
